### ISSUE TITLE
LightningCLI error: trainer.process_position

### ISSUE THREAD

**Issue by vikasTmz** [dasayan05/chirodiff#1]
I get the following error 
```
main.py: error: 'Configuration check failed :: No action for destination key "trainer.process_position" to check its value.'
```

on running `python3.10 main.py --config config.yml fit --model.repr threeseqdel`

My `pytorch-lightning.__version__` == 1.5.9 and[ I believe trainer.process_position wasn't deprecated by then](https://pytorch-lightning.readthedocs.io/en/1.5.10/_modules/pytorch_lightning/trainer/trainer.html).

**Comment by vikasTmz** [comment]
ah, I found my error. I put `fit`, the action, after the config flag and not before.

**Comment by ydyhello** [comment]
> ah, I found my error. I put `fit`, the action, after the config flag and not before.

Hello, I saw on github that you successfully reproduced the code of the paper "ChiroDiff: Modeling chirographic data with Diffusion Models". Did you encounter any of the following problems during the operation?
An error occurs when the command `python main.py fit --config config.yml --model.arch_layer 3 --model.noise_T 100 ...` is entered. The error is as follows:
```
Traceback (most recent call last):
  File "main.py", line 692, in <module>
    cli = LightningCLI(SketchDiffusion, GenericDM, run=True,
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 515, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 551, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 624, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 632, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 594, in _add_arguments
    parser.add_lr_scheduler_args(LR_SCHEDULER_REGISTRY.classes)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 213, in add_lr_scheduler_args
    self.add_subclass_arguments(lr_scheduler_class, nested_key, **kwargs)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/jsonargparse/signatures.py", line 472, in add_subclass_arguments
    doc_group = get_doc_short_description(baseclass[0], logger=self.logger)
IndexError: tuple index out of range
```
