### ISSUE TITLE
The version of jsonargparse

### ISSUE THREAD

**Issue by ydyhello** [dasayan05/chirodiff#2]
Hello, I have the following problem while running the "python main.py fit --config config.yml --model.arch_layer 3 --model.noise_T 100 ..." command. Is this something to do with the jsonargparse version?
```
(M2021-YDY-chirodiff) M2021-YDY@hndx-R8424-G12:~/chirodiff-master$ python main.py fit --config config.yml --model.arch_layer 3 --model.noise_T 100 ...
Traceback (most recent call last):
  File "main.py", line 692, in <module>
    cli = LightningCLI(SketchDiffusion, GenericDM, run=True,
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 515, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 551, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 624, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 632, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 594, in _add_arguments
    parser.add_lr_scheduler_args(LR_SCHEDULER_REGISTRY.classes)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 213, in add_lr_scheduler_args
    self.add_subclass_arguments(lr_scheduler_class, nested_key, **kwargs)
  File "/home/hndx/anaconda3/envs/M2021-YDY-chirodiff/lib/python3.8/site-packages/jsonargparse/signatures.py", line 477, in add_subclass_arguments
    doc_group = get_doc_short_description(baseclass[0], logger=self.logger)
IndexError: tuple index out of range
```
My version of jsonargparse is as follows`jsonargparse             4.21.2`

My Python version is 3.8.17 and pytorch-lightning version is 1.5.9

**Comment by dasayan05** [comment]
Strange! It doesn't look anything on my code. Probably library version issue. BTW my env says it's `jsonargparse == 4.12.0` -- quite older. Maybe give that a try.

**Comment by ydyhello** [comment]
Hello, I am currently checking the configuration file config.yml. In the open source code, except for the following lines, are there any other changes?
'''
...
      entity: # TODO: fill these two ..
      project: # .. entires yourself.
...
    root_dir: # TODO: path to the <category>_<mode>.npz file
...
'''

**Comment by ydyhello** [comment]
Hello, I am currently checking the configuration file config.yml. In the open source code, except for the following lines, are there any other changes?
```
...
entity: # TODO: fill these two ..
project: # .. entires yourself.
...
root_dir: # TODO: path to the _.npz file
...
```

**Comment by cagatayyildiz** [comment]
@ydyhello did you manage to solve this?
