### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by jinge170** [dasayan05/chirodiff#4]
Thanks for you work! when i training follow your guidance, i have a error as follows, can you give me some suggestions? Thank you vey much.

Traceback (most recent call last):
  File "/home/libj/LBJ/chirodiff2/main.py", line 692, in <module>
    cli = LightningCLI(SketchDiffusion, GenericDM, run=True,
  File "/home/libj/.conda/envs/CONTROLNET2/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 515, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/home/libj/.conda/envs/CONTROLNET2/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 551, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/home/libj/.conda/envs/CONTROLNET2/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 624, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
  File "/home/libj/.conda/envs/CONTROLNET2/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 632, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/home/libj/.conda/envs/CONTROLNET2/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 594, in _add_arguments
    parser.add_lr_scheduler_args(LR_SCHEDULER_REGISTRY.classes)
  File "/home/libj/.conda/envs/CONTROLNET2/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 213, in add_lr_scheduler_args
    self.add_subclass_arguments(lr_scheduler_class, nested_key, **kwargs)
  File "/home/libj/.conda/envs/CONTROLNET2/lib/python3.8/site-packages/jsonargparse/_signatures.py", line 503, in add_subclass_arguments
    raise ValueError(f"Expected 'baseclass' argument to be a class or a tuple of classes: {baseclass}")
ValueError: Expected 'baseclass' argument to be a class or a tuple of classes: ()

**Comment by usernameisntavailableble** [comment]
Dont know if it helps, but I changed the package version` pytorch-lightning==2.0.8`, and also adopted some parameters that are not used anymore. Hope that can help.

**Comment by jinge170** [comment]
First thanks for the answer, I've modified the code according to your prompt but it  doesn't work, can you share your code with me if it's convenient for you? Thank you very much!

**Comment by jinge170** [comment]
2020903343@qq.com that's my email🙇‍
